title: Zmplr
description: A family of .NET libraries built in the spirit of as simple as possible, but no simpler.
theme: jekyll-theme-cayman
baseurl: /zmplr
url: https://mtanneryd.github.io
show_downloads: false
